### ISSUE TITLE
Checking the return value of malloc().

### ISSUE THREAD

**Issue by kemonats** [phoenix-rtos/phoenixd#7]
Is there any rule when it is checked if 'malloc()' returned 'NULL'.
As I can see in the code once it is checked, another time it doesn't.

**Comment by agkaminski** [comment]
Of course the rule is that the return value of malloc() shall be checked for NULL. There're some instances of optimistic programming in this repository that we'll fix as soon as possible. Thank you.

**Comment by kemonats** [comment]
In this repository this is probably not so critical, but in the phoenix-rtos-devices repository, yes.
I reviewed the code in this repository and in phoenix-rtos-devices and I have some more general insights.
If you are interested in my observations, I can present them.
